apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: lblhttpd
spec:
  replicas: 10
  selector:
    matchLabels:
      app: lblhttpd
  template:
    metadata:
      labels:
        app: lblhttpd
    spec:
      containers:
      - name: nginx
        image: nginx
