apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-nginx-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lblng
  template:
    metadata:
      labels:
        app: lblng
    spec:
      containers:
      - name: nginx
        image: nginx
